### ISSUE TITLE
Create a display function/class.

### ISSUE THREAD

**Issue by MarkusJCollection** [MarkusJCollection/UnitConverter#6]

**Comment by MarkusJCollection** [comment]
Never mind, everything's fine. I was getting an error and it acted like static was causing issues, but it seems it's completely fine. Sorry for that.

**Comment by MarkusJCollection** [comment]
> Never mind, everything's fine. I was getting an error and it acted like static was causing issues, but it seems it's completely fine. Sorry for that.

Allowed me to actually figure out what static means, I didn't have a full understand of it before.

**Comment by Smichels27** [comment]
IT's all right, just let me know if there's anything else i can do/
